version: 20.10.0
services:
  psql451: 
    image: postgress
    envirnomnent:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:   
      - /Users/hathawayj/docker/postgresql:/var/lib/postgresql/data 
      - /Users/hathawayj/docker/extshare:/extshare 
    ports:
      - '5432:5432'
    networks:
      - n451

  spark451:
    image: jupyter/all-spark-notebook
    depends_on:
      - psql451
    ports:
      - '888:8888'
      - '4040:4040' 
      - '4041:4041'
    volumes:
      - /Users/hathawayj/docker:/home/jovyan/cse451
    networks:
      - n451

  adminer451:
    image: adminer
    depends_on:
      - psql451
    ports:
      - '8080:8080'
    networks:
      - n451
